
[ClassVersion("1.0.0.0"), FriendlyName("RunbookDirectory")]
class xRunbookDirectory : OMI_BaseResource
{
    [Key] String RunbookPath;
    [Write] Boolean Publish;
    [Read] Boolean Matches;
    [Required] String WebServiceEndpoint;
    [Write] Uint32 Port;
};

